version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
  pre_build:
    commands:
      - echo "Setting timezone to Asia/Kolkata..."
      - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
      - export TZ=Asia/Kolkata
      - date  # Just to verify it’s set correctly
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build & packaging completed."
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'

# this is a yaml file